name: Pylint Workflow on Ubuntu

on:
  issue_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - main

jobs:
  lint-diff:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/lint')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies and pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt || echo "Skipping install errors (e.g., Windows-only deps)"

      - name: Get changed Python files
        id: changed-files
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          echo "Fetching changed files for PR #$PR_NUMBER"
          FILES=$(gh pr diff "$PR_NUMBER" --name-only | grep '\.py$' || true)
          echo "$FILES"
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pylint on changed files
        id: pylint-diff
        run: |
          FILES="${{ steps.changed-files.outputs.changed_files }}"
          if [ -z "$FILES" ]; then
            echo "No Python files changed."
            echo "pylint_score=10.0" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Running pylint on the following files:"
          echo "$FILES"
          OUTPUT=$(pylint $FILES --rcfile=.pylintrc --disable=import-error --score=y 2>&1)
          echo "$OUTPUT"
          SCORE_LINE=$(echo "$OUTPUT" | grep "Your code has been rated at")
          if [ -n "$SCORE_LINE" ]; then
            SCORE=$(echo "$SCORE_LINE" | awk '{print $7}' | cut -d'/' -f1)
          else
            echo "Failed to parse pylint score."
            SCORE=0
          fi
          echo "Pylint score: $SCORE"
          echo "pylint_score=$SCORE" >> $GITHUB_OUTPUT
          if (( $(echo "$SCORE < 9.5" | bc -l) )); then
            exit 1
          fi

      - name: Comment PR with pylint result
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **Pylint score on changed files**: **${{ steps.pylint-diff.outputs.pylint_score }}**

            _Threshold to pass: 9.5_

  lint-full:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies and pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt || echo "Skipping install errors (e.g., Windows-only deps)"

      - name: Run pylint on full codebase
        id: pylint-full
        run: |
          FILES=$(git ls-files '*.py')
          if [ -z "$FILES" ]; then
            echo "No Python files found."
            echo "pylint_score=10.0" >> $GITHUB_OUTPUT
            exit 0
          fi
          OUTPUT=$(pylint $FILES --rcfile=.pylintrc --disable=import-error --score=y 2>&1 || true)
          echo "$OUTPUT"
          SCORE_LINE=$(echo "$OUTPUT" | grep "Your code has been rated at")
          if [ -n "$SCORE_LINE" ]; then
            SCORE=$(echo "$SCORE_LINE" | awk '{print $7}' | cut -d'/' -f1)
          else
            echo "Failed to parse pylint score."
            SCORE=0
          fi
          echo "Full Pylint score: $SCORE"
          echo "pylint_score=$SCORE" >> $GITHUB_OUTPUT
          if (( $(echo "$SCORE < 9.7" | bc -l) )); then
            exit 1
          fi

      - name: Final status
        run: echo "✅ Full codebase Pylint check passed with score ${{ steps.pylint-full.outputs.pylint_score }}"
